MEN-2174: Fix regression of missing port info in http redirect urls
mendersoftware/mender-api-gateway-docker pull request #160
Opened 2020-12-18 15:44 UTC by dellgreen

Signed-off-by: Dell Green <dell.green@ideaworks.co.uk>

https://tracker.mender.io/browse/MEN-2174
https://tracker.mender.io/browse/MEN-1264

2021-01-12 13:31 UTC, dellgreen commented
when you get a chance, can some one please review this trivial fix, as it would save me from maintaining a fork of this docker image just for this, much appreciated in advance :)

2021-01-12 14:19 UTC, tranchitella commented
@dellgreen I'll review your PR, sorry for the delay

2021-01-12 14:57 UTC, dellgreen commented
> @dellgreen I'll review your PR, sorry for the delay

awesome thank you :+1:

2021-01-14 09:25 UTC, tranchitella requested changes

2021-01-14 09:25 UTC, tranchitella commented on common.nginx.conf
> +	return 301 https://$http_host/ui/;
Instead of hard-coding https, you should rely on `$scheme`. We support the possibility to run the Mender API gateway in HTTP mode, indeed. Please also check what is happening when the Host header contains a non-custom port. According to the documentation, `$http_host` should contain the port number but in local my tests it did not work.

2021-01-14 15:28 UTC, dellgreen commented on common.nginx.conf
> +	return 301 https://$http_host/ui/;
Ok thank you for the feedback, I'll take a look into the changes

2021-04-29 07:41 UTC, tranchitella commented
@dellgreen Mender 2.7 switched from openresty/nginx to Traefik. I believe we can close this PR, what do you think?

2021-04-29 09:18 UTC, dellgreen commented
> @dellgreen Mender 2.7 switched from openresty/nginx to Traefik. I believe we can close this PR, what do you think?

Yes, it makes sense to close it

2021-04-29 09:42 UTC, closed without merging